# Generated by Django 2.1.2 on 2020-01-25 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('extra_fields', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('goals', models.TextField()),
                ('requirements', models.TextField()),
                ('stage', models.CharField(choices=[('Design', 'Design'), ('Ready', 'Ready'), ('Delete', 'Delete'), ('FixIt', 'FixIt')], default='Design', max_length=6)),
                ('pre_conditions', models.TextField()),
                ('variants', models.TextField()),
                ('steps', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('step_name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=1000)),
                ('chain_test_id', models.CharField(max_length=1000)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.NewTestCase')),
            ],
        ),
    ]
