# Generated by Django 2.1.2 on 2018-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ololo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
