# Generated by Django 2.1.2 on 2020-04-06 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_stepsresults_chain_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Case')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
    ]
