# Generated by Django 2.1.2 on 2018-10-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181008_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pre_conditions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='post',
            name='variants',
        ),
    ]
