# Generated by Django 2.1.2 on 2020-01-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181008_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ololo',
        ),
    ]
