# Generated by Django 2.1.2 on 2020-01-08 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_remove_post_ololo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='NewTestCase',
        ),
    ]
