# Generated by Django 2.1.2 on 2020-04-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200423_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=1000)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.NewTestCase')),
            ],
            options={
                'ordering': ['tags'],
            },
        ),
        migrations.RemoveField(
            model_name='steps',
            name='tags',
        ),
    ]
