# Generated by Django 2.1.2 on 2020-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200423_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtestcase',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='testcasetag',
            name='test_case',
        ),
        migrations.AddField(
            model_name='newtestcase',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tags for this test-case', to='blog.TestCaseTag'),
        ),
    ]
