# Generated by Django 2.1.2 on 2020-05-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200510_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtestcase',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='isbn_number',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='pre_conditions',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='text',
        ),
        migrations.RemoveField(
            model_name='newtestcase',
            name='variants',
        ),
    ]
