# Generated by Django 2.1.2 on 2020-05-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200510_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
