# Generated by Django 2.1.2 on 2020-05-10 14:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blog', '0013_auto_20200510_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TestCaseTag',
        ),
    ]
