# Generated by Django 2.1.2 on 2020-05-10 14:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blog', '0014_auto_20200510_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCaseTag',
            new_name='Tag',
        ),

    ]

