# Generated by Django 2.1.2 on 2020-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200510_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestcase',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tags for this test-case', related_name='tags', to='blog.Tag'),
        ),
    ]
