# Generated by Django 2.1.2 on 2020-05-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200511_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='case',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='stepsresults',
            name='test_case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='StepsResults',
        ),
    ]
