# Generated by Django 2.1.2 on 2020-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200511_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_style',
            field=models.CharField(choices=[('df', 'btn btn-default'), ('db', 'btn btn-primary'), ('gr', 'btn btn-success'), ('bl', 'btn btn-info'), ('or', 'btn btn-warning'), ('rd', 'btn btn-danger')], default='df', max_length=2),
        ),
    ]
