# Generated by Django 2.1.2 on 2020-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_tag_tag_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_style',
            field=models.CharField(choices=[('btn btn-default', 'default (gray)'), ('btn btn-primary', 'dark blue'), ('btn btn-success', 'green'), ('btn btn-info', 'blue'), ('btn btn-warning', 'orange'), ('btn btn-danger', 'red')], default='btn btn-default', max_length=20),
        ),
    ]
